####
# General Config
####

# For now, appveyor build version is not equal to app version - it's just a sequentially increasing number.
version: 1.0.{build}

# The goal is to build and deploy occasional release milestones to GitHub.
# Rather than building every commit to master, we'll only build when merging into release branch.
#branches:
#  only:
#    - release

# Do not build tags.
skip_tags: true

# I think this is a limitation of the free plan anyway!
max_jobs: 1

####
# Environment Config
####

# Build for Windows and Mac.
image: 
  - macos
  - Visual Studio 2019

# Init script runs before cloning the repo.
#init:
#  - echo Init

# Install scripts run after cloning completes.
#install:
#  - echo Install

####
# Build Config
####
configuration: RelWithDebInfo

# Scripts to run before build.
before_build:
  # For Mac: generate Xcode project.
  - sh: cmake -B build -G Xcode .
  
  # For Windows: when you open VS, it generates a CMake "build" directory based on the contents of CMakeSettings.json.
  # Unfortunately, there's no way to execute what VS does (or use CMakeSettings.json) from the command line.
  # As a workaround, execute the cmake command that VS exectutes (pulled from VS CMake output log).
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
  - cmd: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="%CONFIGURATION%" -DCMAKE_C_COMPILER:FILEPATH="cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="cl.exe" -DCMAKE_MAKE_PROGRAM="ninja.exe" .
  #- cmd: cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE:STRING="RelWithDebInfo" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx86/x86/cl.exe" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" .

build_script:
  # For Mac: build project using xcodebuild "deploy" target. (TODO: can "cmake --build" be used here as well?)
  # xcodebuild only works IN THE DIRECTORY with the Xcode project, which is why we must "cd" in and out.
  - sh: cd build
  - sh: xcodebuild -target deploy -configuration "${CONFIGURATION}"
  - sh: cd ../

  # For Windows: use the built-in CMake "build" command to compile using Ninja. 
  - cmd: cmake --build build --target deploy

# Scripts to run after build.
after_build:
  - echo After Build

####
# Tests Config
####

# Scripts to run before tests.
before_test:
  # For Mac: build test target.
  - sh: cd build
  - sh: xcodebuild -target tests -configuration "${CONFIGURATION}"
  - sh: cd ../

  # For Windows: build test target.
  - cmd: cmake --build build --target tests

# Scripts to run for tests.
test_script:
  # For Mac: run tests.
  - sh: ./build/Tests/${CONFIGURATION}/tests

  # For Windows: run tests.
  - cmd: build\Tests\tests.exe

# Scripts to run after tests.
after_test:
  - echo After Tests

####
# Artifact Config
####

# Build scripts will leave ready-to-deploy app in "Bin" folder 
artifacts:
  - path: Bin/$(configuration)/*.zip

####
# Deployment Config
####

# Scripts to run before deployment.
before_deploy:
  - echo Before Deploy

# Scripts to be run for deployment.
deploy_script:
  - echo Deploy

# Appveyor's "automatic deploy" step. 
# Allows deploying to many destinations without writing custom scripts.
#deploy:
#  - provider: GitHub
#    artifact: /*\.zip/
#    draft: false
#    prerelease: false
#    on:
#      branch: release

# Scripts to run after deployment.
after_deploy:
  - echo After Deploy

####
# Handlers
####

# Scripts to run on successful build completion.
on_success:
  - echo Success

# Scripts to run on build failure.
on_failure:
  - echo Failure

# Scripts to run on build finish (success or failure).
on_finish:
  - echo Finish

####
# Notifications
####

# A way to send a notif (email, Slack, etc) when a build finishes.
# Just to test it out, I'll send myself an email on build status change.
notifications:
  - provider: Email
    to:
      - kromenak@gmail.com
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}"
    on_build_failure: true
    on_build_status_changed: true